apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    10: 
      - .*inteld8sv5*
    20: 
      - .*amdd8asv5*
    50: 
      - .*amdd32asv5*